#include <iostream>
#include <cstdlib>
#include <ctime>
#include <fstream>
#include <unistd.h>
#include <vector>
#include <string>
#include "player.h"
#include "game.h"
#include "utils.h"
#include <algorithm>
#ifdef _WIN32
    #include <windows.h>
    #include <conio.h>
    #define SLEEP(ms) Sleep(ms)
    #define CLEAR_SCREEN() system("cls")
    #define GETCH() _getch()
#else
    #include <termios.h>
    #define SLEEP(ms) usleep(ms * 1000)
    #define CLEAR_SCREEN() system("clear")
    char getch() {
        struct termios oldt, newt;
        char ch;
        tcgetattr(STDIN_FILENO, &oldt);
        newt = oldt;
        newt.c_lflag &= ~(ICANON | ECHO);
        tcsetattr(STDIN_FILENO, TCSANOW, &newt);
        ch = getchar();
        tcsetattr(STDIN_FILENO, TCSANOW, &oldt);
        return ch;
    }
    #define GETCH() getch()
#endif

using namespace std;

void tips123(){
    CLEAR_SCREEN();
    cout << "Welcome to Terminal Intruder!"<<endl;
    cout << "You can input 'wasd' to control character (p) movement. 'm' to clear mines, 'save' to save the game, 'q' to exit the" << endl;
    cout << "game, and 'e' to interact with the door, if you want to check tips again, you also can input 'tips' angain during the game.\n" <<endl;

    cout << "In this game, you need to find the exit door (D) of the maze (which is hidden) and collect enough keys to clear it.\n" << endl;

    cout << "All the keys are hidden inside the mysterious door (?) (also hidden), and you need to pass through the funny test\ninside the mysterious door to get the key to open the exist door.\n" << endl;
    
    cout << "However, you need to be aware that there are many mines (X) buried in the maze. Fortunately, you have the ability" << endl; 
    cout << "to detect the number of all mines within a 5 * 5 range around you (displayed in the bottom right corner of the screen)," << endl;
    cout << "and you can enter 'm' to clear all mines within a 3*3 range around you (which means you have a chance to clear three" <<endl;
    cout << "mines at one time)\n" << endl;

    cout << "This game has three built-in game difficulty levels: easy, normal, and hard. But if you want to challenge a higher level" << endl;
    cout << "of difficulty, you can also choose the size of the map yourself, but it is important to remember that the size of the map" << endl;
    cout << "must be odd and not exceed the specified maximum value (otherwise display errors may occur)\n" << endl;
    
    cout << "Author's words: 'Remember, this game requires good memory and intelligence, use your brain to find the solution!!! :)" << endl;
    cout << "I guarantee that every map has a solution. You can determine which row or column has mines by constantly moving your" << endl; 
    cout << "character and check the mine number, which is completely different from normal Minesweeping O.o'\n" << endl;
    
    cout << "You have already understood the content of this game, go and give it a try !!!!!!" << endl;
    return;
}

// The title is generated by https://www.ascii-art-generator.org/
void DisplayTitle() {
    string line;
    ifstream fin;
    fin.open("GameTitle.txt");
    while (getline(fin, line)){
        cout << line << endl;
        usleep(250000);
    }
    cout << "\033[32m-Welcome to Terminal Intruder! The maze has been waiting for you-\033[0m" << endl << endl;
    fin.close();
    SLEEP(3000); 
}

// Four options in the home page
void GameChoice() {
    cout << "\033[46mN\033[0m: New Game" << endl;
    cout << "\033[44mS\033[0m: Saved Game" << endl;
    cout << "\033[30;47mT\033[0m: Helpful Tips" << endl;
    cout << "\033[43mQ\033[0m: Quit" << endl;
    
    cout << endl << "\033[3mWhere do you want to start your adventure?\033[0m" << endl;
    cout << endl << "\033[2mChoices are case-insensitive: Both 'N' and 'n' are fine.\033[0m" << endl;
    cout << endl;
} 

// Structure for linking different parts of the game
void HomePage(){
    DisplayTitle();
    GameChoice();
    string line;
    ifstream fin;
    bool sta;

    char choice; 
    cin >> choice;
    while (choice != 'Q' && choice != 'q') {
        CLEAR_SCREEN();
        fin.open("GameTitle.txt");
        while (getline(fin, line)){
            cout << line << endl;
        }
        cout << "\033[32m-Welcome to Terminal Intruder! The maze has been waiting for you-\033[0m" << endl << endl;
        fin.close();
        GameChoice();
        if (choice == 'N' || choice == 'n') {
            sta = game("n");
        } else if (choice == 'S' || choice == 's') {
            PrintSaved();
            string filename;
            if (NameSaved.size()>0){
                while(true){
                    cin >> filename;
                    auto it = find(NameSaved.begin(), NameSaved.end(), filename);
                    if(filename == "q"){
                        sta = true;
                        CLEAR_SCREEN();
                        break;
                    }
                    if(it != NameSaved.end()){
                        sta = game(filename);
                    }
                }
            }
        } else if (choice == 'T' || choice == 't') {
            tips123();
            string a;
            if (cin >> a){
                CLEAR_SCREEN();
                sta = true;
            }
        } else {
            cout << "Invalid starting point. Please try again." << endl;
        }
        if (sta){
            fin.open("GameTitle.txt");
            while (getline(fin, line)){
                cout << line << endl;
            }
            cout << "\033[32m-Welcome to Terminal Intruder! The maze has been waiting for you-\033[0m" << endl << endl;
            fin.close();
            GameChoice();
            sta=false;
        }
        cin >> choice;
    }
    
    cout << endl << "\033[3mHope to See You Soon!\033[0m" << endl;
}

void setColor(int color) {
    #ifdef _WIN32
        SetConsoleTextAttribute(GetStdHandle(STD_OUTPUT_HANDLE), color);
    #else
        const char* colors[] = {"\033[30m", "\033[31m", "\033[32m", "\033[33m", "\033[34m", "\033[35m", "\033[36m", "\033[37m"};
        cout << colors[color % 8];
    #endif
}

void initConsole() {
    #ifdef WIN32
        system("mode con cols=60 lines=30");
    #endif
    CLEAR_SCREEN();
}

// Provide random tips for players to kill time while they're waiting
string random_tips() {
    vector <string> lines = {
        "You will discover that after finishing reading this line you can start to play the game.",
        "Still confused about the game? Check out our introductory video and see if you'll get inspired!",
        "Thanks for playing the game and have fun in the maze!",
        "Find the game a bit hard? Try seeking tips at home page of the game.",
        "There are actually treasures in the maze. Don't forget to find them while getting out of levels!",
        "Get stuck in the previous level? How about start a new game to refresh your mind?",
        "Fun fact: Harry Potter's Triwizard Maze in Goblet of Fire was inspired by English garden mazes.",
        "Fun fact: Hall of Mirrors mazes use angled mirrors to create infinite reflections.",
        "Find anything fun in the maze? If so, well done!",
        "Get ready for exploring the maze?"
    };
    
    srand(static_cast<unsigned int>(time(0)));
    int randomIndex = rand() % lines.size();
    return lines[randomIndex];

}

// Main body of the loading process
void showLoadingBar() {
    setColor(8); // Gray
    cout << "[";
    for (int i = 0; i < 20; i++) {
        setColor(10 + (i % 2)); // Blinking green
        cout << "■";
        SLEEP(50 + rand() % 100);
    }
    setColor(8);
    cout << "]" << endl;
    setColor(7); // White
}
void showLoadingScreen() {
    initConsole();
    srand(time(0));
    
    setColor(11);
    cout << "\n\n Preparing maze adventure...\n\n";
    
    showLoadingBar();
    
    setColor(14);
    cout << "\n Loading complete!\n";
    SLEEP(500);
    
    setColor(7);
    cout << "\n Press any key to continue...";
    GETCH();

    CLEAR_SCREEN();
}

char difficulty_of_the_quanbuyouxi= '0';

char chooseDifficulty(){
    pair<int, int> terminalSize = getTerminalSize();
    int termWidth = terminalSize.first;
    string space(termWidth, ' ');
    string space1((termWidth-7)/2, ' ');
    string space2((termWidth-9)/2, ' ');
    string space3((termWidth-14)/2, ' ');
    cout<<"\033[42m"<<space<<space1<<"Esay: e"<<space1<<space<<"\033[0m" << "\033[43m"<<space<<space2<<"Normal: n"<<space2<<space<<"\033[0m" << "\033[41m"<<space<<space1<<"Hard: h"<<space1<<space<<"\033[0m" <<"\033[44m"<<space<<space3<<"Free choice: f"<<space3<<space<<"\033[0m"<<"\n\n"<<space<<"Quit: q"<<endl;
    string diff;
    cin >> diff;
    if(diff == "e"){
        difficulty_of_the_quanbuyouxi = '1';
        return '1';
    }
    else if(diff == "n"){
        difficulty_of_the_quanbuyouxi = '2';
        return '2';
    }
    else if(diff == "h"){
        difficulty_of_the_quanbuyouxi = '3';
        return '3';
    }
    else if(diff == "f"){
        difficulty_of_the_quanbuyouxi = '3';
        return '4';
    }
    else if(diff == "q"){
        return '5';
    }
    else{
        cout << "Invalid input, please try again." << endl;
        CLEAR_SCREEN(); 
        return chooseDifficulty();
    }
}

vector <int> getXY(){
    cout << "\033[2J\033[H";
    int diff = chooseDifficulty();
    cout << "\033[2J\033[H";
    if (diff == '1'){
        player_heart = 3;
        return {11, 11};
    }
    else if(diff == '2'){
        player_heart = 5;
        return {15, 15};
    }
    else if(diff == '3'){
        player_heart = 8;
        return {31, 19};
    }
    else if(diff == '4'){
        int x,y;
        while (true){
            cout<<"Please enter the size you want to challenge, please both bigger than 7(x(max:131)and y(max:21))\nONLY OOD!!!!!!!"<<endl;
            cin >> x >> y;
            if (x%2==0||y%2==0||x<7||y<7||y>21||x>131){
                cout << "\033[2J\033[H";
                cout << "you can just enter odd number and bigger than 7, please try again!" << endl;
                continue;
            }
            break;
        }
        cout << "please enter your heart number" << endl;
        getHeart();
        cout << "\033[2J\033[H";
        return {x,y};
    }
    else if(diff == '5'){
        CLEAR_SCREEN(); 
        return {100000, 100000};
    }
    else{
        cout << "Invalid input, please try again." << endl;
        CLEAR_SCREEN(); 
        return getXY();
    }
}
